apiVersion: v1
kind: Service
metadata:
  name: notifications-api-service
  namespace: default
  labels:
    app: notifications-api
spec:
  type: ClusterIP
  selector:
    app: notifications-api
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
